  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    restart: always
    depends_on:
      - db
    ports:
      - "8002:8002"
    volumes:
      - $HOME/docker/volumes/breads:/var/lib



